## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_Internet-Gateway-vcn-oz2h {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:50.985Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "Internet Gateway-vcn-oz2h"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn-oz2h.id
}

resource oci_core_subnet export_Private-Subnet-vcn-oz2h {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:50.961Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  dhcp_options_id = oci_core_vcn.export_vcn-oz2h.default_dhcp_options_id
  display_name    = "Private Subnet-vcn-oz2h"
  dns_label       = "sub02041234451"
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_Route-Table-for-Private-Subnet-vcn-oz2h.id
  security_list_ids = [
    oci_core_security_list.export_Security-List-for-Private-Subnet-vcn-oz2h.id,
  ]
  vcn_id = oci_core_vcn.export_vcn-oz2h.id
}

resource oci_core_subnet export_Public-Subnet-vcn-oz2h {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:51.139Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  dhcp_options_id = oci_core_vcn.export_vcn-oz2h.default_dhcp_options_id
  display_name    = "Public Subnet-vcn-oz2h"
  dns_label       = "sub02041234450"
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_vcn-oz2h.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_vcn-oz2h.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcn-oz2h.id
}

resource oci_core_vcn export_vcn-oz2h {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:49.503Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "vcn-oz2h"
  dns_label    = "vcnoz2h"
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_nat_gateway export_NAT-Gateway-vcn-oz2h {
  block_traffic  = "false"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:51.001Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "NAT Gateway-vcn-oz2h"
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  public_ip_id = "ocid1.publicip.oc1.iad.aaaaaaaavl65llnr36owcyo2jvme34z424xfxnwzaj7kaitlik7xgdme5jwq"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn-oz2h.id
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-vcn-oz2h {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:49.503Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name     = "Default DHCP Options for vcn-oz2h"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  manage_default_resource_id = oci_core_vcn.export_vcn-oz2h.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcnoz2h.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_security_list export_Security-List-for-Private-Subnet-vcn-oz2h {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:51.568Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "Security List for Private Subnet-vcn-oz2h"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_vcn-oz2h.id
}

resource oci_core_default_security_list export_Default-Security-List-for-vcn-oz2h {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:49.503Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "Default Security List for vcn-oz2h"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_vcn-oz2h.default_security_list_id
}

resource oci_core_service_gateway export_Service-Gateway-vcn-oz2h {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:51.104Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "Service Gateway-vcn-oz2h"
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_vcn-oz2h.id
}

resource oci_core_private_ip export_instance-20230204-0735 {
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:36:26.461Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "instance-20230204-0735"
  freeform_tags = {
  }
  hostname_label = "instance-20230204-0735"
  ip_address     = "10.0.0.40"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljt5uwfnlttbdnwwlyyqcqmw4x4ryadvalqzvsobvvmauokh6bwqzkq"
}

resource oci_core_route_table export_Route-Table-for-Private-Subnet-vcn-oz2h {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:51.071Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "Route Table for Private Subnet-vcn-oz2h"
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT-Gateway-vcn-oz2h.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_Service-Gateway-vcn-oz2h.id
    #route_type = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_vcn-oz2h.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-vcn-oz2h {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:34:49.503Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "Default Route Table for vcn-oz2h"
  freeform_tags = {
    "VCN" = "VCN-2023-02-04T12:34:23"
  }
  manage_default_resource_id = oci_core_vcn.export_vcn-oz2h.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-vcn-oz2h.id
    #route_type = <<Optional value not found in discovery>>
  }
}

resource oci_core_instance export_instance-20230204-0735_1 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Java Management Service"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = var.availability_domain--YxuQ-US-ASHBURN-AD-1
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Standard.CostCenter" = "johanna.gutierrez"
      "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
      "Oracle-Tags.CreatedOn"      = "2023-02-04T12:36:26.461Z"
      "Schedule.SHUTDOWN"          = "Yes"
    }
    display_name = "instance-20230204-0735"
    freeform_tags = {
    }
    hostname_label = "instance-20230204-0735"
    nsg_ids = [
    ]
    private_ip             = "10.0.0.40"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_Public-Subnet-vcn-oz2h.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Standard.CostCenter" = "johanna.gutierrez"
    "Oracle-Tags.CreatedBy"      = "default/max.parra@oracle.com"
    "Oracle-Tags.CreatedOn"      = "2023-02-04T12:36:26.248Z"
    "Schedule.SHUTDOWN"          = "Yes"
  }
  display_name = "instance-20230204-0735"
  extended_metadata = {
  }
  fault_domain = var.fault_domain--FAULT-DOMAIN-3
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfAlRP9OJducfZ5VHjtqg7M8uU3mauKDz20rGu/efbs2zSOVtZ+Ly9/Davq2lddwgAQhg8kWdRTr2Scezwg+yJasB2gRQ4NPEiZjTpkLrqaaTf7QgRdlSdzEMUDV1hsXLfCU3tusX1w+1D9ft/AqOi6KBwJ8MzT9LNxFrAj7NEssuEctlB8XCLuqe7OCbH5AKY/nyk9c0Xciyxp28BOCySvan0TpOrVn5tMTCsn1JXDdIPKg5T9VegQW93XAtw3d+mQM1NXuGWx6yHbJmtveXB2pFkOBfPHIuF70qUgitplJ2LfW1ULY0zxcSML/LOj2JUemTkJTLLvpDyZmwum0Td ssh-key-2023-02-04"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.A1.Flex"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "6"
    nvmes                     = "0"
    ocpus                     = "1"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    boot_volume_vpus_per_gb = "10"
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.oci_core_instance--source_details-source_id--export_instance-20230204-0735_1
    source_type = "image"
  }
  state = "RUNNING"
}

